version: '3.1'

services:
    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: serversider
            MYSQL_ROOT_PASSWORD: wow-such-hard-to-hack
